/**
 * US-294 vitest fixtures.
 *
 * Five anonymized receipt JSON outputs that mirror what the
 * parse-receipt-image edge function returns for representative merchants.
 * Values are realistic (line counts + structure) but no real customer
 * data is embedded. Used by receiptParse.test.ts.
 */
import type { ParseResponse } from './receiptParse';

export const wholeFoodsFixture: ParseResponse = {
  merchant: 'Whole Foods',
  purchasedAt: '2026-05-08',
  currency: 'USD',
  lineItems: [
    {
      rawText: 'ORG BANANAS 1.32LB',
      parsedName: 'Bananas',
      qty: 1.32,
      unit: 'lb',
      unitPrice: 0.79,
      lineTotal: 1.04,
      category: 'fruit',
      confidence: 0.92,
    },
    {
      rawText: 'ORG SPINACH 5OZ',
      parsedName: 'Spinach',
      qty: 1,
      unit: 'pack',
      unitPrice: 4.99,
      lineTotal: 4.99,
      category: 'vegetable',
      confidence: 0.88,
    },
    {
      rawText: '365 WHOLE MILK GAL',
      parsedName: 'Whole Milk',
      qty: 1,
      unit: 'gal',
      unitPrice: 4.49,
      lineTotal: 4.49,
      category: 'dairy',
      confidence: 0.95,
    },
    {
      rawText: 'BLUEBERRIES PINT',
      parsedName: 'Blueberries',
      qty: 1,
      unit: 'pint',
      unitPrice: 4.99,
      lineTotal: 4.99,
      category: 'fruit',
      confidence: 0.9,
    },
    {
      rawText: 'CHICKEN BREAST 1.85LB',
      parsedName: 'Chicken Breast',
      qty: 1.85,
      unit: 'lb',
      unitPrice: 6.99,
      lineTotal: 12.93,
      category: 'protein',
      confidence: 0.87,
    },
    {
      rawText: 'PASTURE RAISED EGGS DOZ',
      parsedName: 'Eggs',
      qty: 1,
      unit: 'dozen',
      unitPrice: 6.49,
      lineTotal: 6.49,
      category: 'protein',
      confidence: 0.94,
    },
    {
      rawText: 'AVOCADO EACH',
      parsedName: 'Avocado',
      qty: 2,
      unit: 'ea',
      unitPrice: 1.5,
      lineTotal: 3.0,
      category: 'fruit',
      confidence: 0.83,
    },
    {
      rawText: 'YOGURT GREEK 32OZ',
      parsedName: 'Greek Yogurt',
      qty: 1,
      unit: 'jar',
      unitPrice: 5.99,
      lineTotal: 5.99,
      category: 'dairy',
      confidence: 0.91,
    },
  ],
};

export const aldiFixture: ParseResponse = {
  merchant: 'Aldi',
  purchasedAt: '2026-05-09',
  currency: 'USD',
  lineItems: [
    {
      rawText: 'CARLINI OLIVE OIL 17OZ',
      parsedName: 'Olive Oil',
      qty: 1,
      unit: 'bottle',
      unitPrice: 4.49,
      lineTotal: 4.49,
      category: 'pantry',
      confidence: 0.86,
    },
    {
      rawText: 'MILLVILLE OATS 18OZ',
      parsedName: 'Oats',
      qty: 1,
      unit: 'box',
      unitPrice: 2.49,
      lineTotal: 2.49,
      category: 'carb',
      confidence: 0.84,
    },
    {
      rawText: 'KIDS BANANAS 3LB',
      parsedName: 'Bananas',
      qty: 3,
      unit: 'lb',
      unitPrice: 0.49,
      lineTotal: 1.47,
      category: 'fruit',
      confidence: 0.92,
    },
    {
      rawText: 'GOAT CHEESE 4OZ',
      parsedName: 'Goat Cheese',
      qty: 1,
      unit: 'pack',
      unitPrice: 3.49,
      lineTotal: 3.49,
      category: 'dairy',
      confidence: 0.78,
    },
    {
      rawText: 'PASTA PENNE 16OZ',
      parsedName: 'Penne Pasta',
      qty: 1,
      unit: 'box',
      unitPrice: 1.19,
      lineTotal: 1.19,
      category: 'carb',
      confidence: 0.89,
    },
    {
      rawText: 'GROUND BEEF 1LB',
      parsedName: 'Ground Beef',
      qty: 1,
      unit: 'lb',
      unitPrice: 4.99,
      lineTotal: 4.99,
      category: 'protein',
      confidence: 0.9,
    },
  ],
};

export const walmartFixture: ParseResponse = {
  merchant: 'Walmart',
  purchasedAt: '2026-05-10',
  currency: 'USD',
  lineItems: [
    {
      rawText: 'GV WHOLE MILK GAL',
      parsedName: 'Whole Milk',
      qty: 1,
      unit: 'gal',
      unitPrice: 3.48,
      lineTotal: 3.48,
      category: 'dairy',
      confidence: 0.93,
    },
    {
      rawText: 'WONDER BREAD',
      parsedName: 'Bread',
      qty: 1,
      unit: 'loaf',
      unitPrice: 2.78,
      lineTotal: 2.78,
      category: 'carb',
      confidence: 0.85,
    },
    {
      rawText: 'EGGS LARGE 18CT',
      parsedName: 'Eggs',
      qty: 1,
      unit: 'pack',
      unitPrice: 4.18,
      lineTotal: 4.18,
      category: 'protein',
      confidence: 0.91,
    },
    {
      rawText: 'GOLDFISH CHEDDAR',
      parsedName: 'Goldfish',
      qty: 1,
      unit: 'bag',
      unitPrice: 2.97,
      lineTotal: 2.97,
      category: 'snack',
      confidence: 0.88,
    },
    {
      rawText: 'APPLE GALA 3LB',
      parsedName: 'Gala Apples',
      qty: 3,
      unit: 'lb',
      unitPrice: 0.97,
      lineTotal: 2.91,
      category: 'fruit',
      confidence: 0.92,
    },
    {
      rawText: 'CHICKEN THIGHS 2.5LB',
      parsedName: 'Chicken Thighs',
      qty: 2.5,
      unit: 'lb',
      unitPrice: 2.97,
      lineTotal: 7.42,
      category: 'protein',
      confidence: 0.84,
    },
    {
      rawText: 'PEANUT BUTTER 16OZ',
      parsedName: 'Peanut Butter',
      qty: 1,
      unit: 'jar',
      unitPrice: 2.48,
      lineTotal: 2.48,
      category: 'pantry',
      confidence: 0.88,
    },
    {
      rawText: 'PAPER TOWELS 6CT',
      parsedName: 'Paper Towels',
      qty: 1,
      unit: 'pack',
      unitPrice: 8.97,
      lineTotal: 8.97,
      category: 'household',
      confidence: 0.94,
    },
    {
      rawText: 'JUICE BOX 8PK',
      parsedName: 'Juice Box',
      qty: 1,
      unit: 'pack',
      unitPrice: 3.28,
      lineTotal: 3.28,
      category: 'beverage',
      confidence: 0.86,
    },
    {
      rawText: 'BABY CARROTS 1LB',
      parsedName: 'Baby Carrots',
      qty: 1,
      unit: 'bag',
      unitPrice: 1.18,
      lineTotal: 1.18,
      category: 'vegetable',
      confidence: 0.93,
    },
  ],
};

export const traderJoesFixture: ParseResponse = {
  merchant: "Trader Joe's",
  purchasedAt: '2026-05-11',
  currency: 'USD',
  lineItems: [
    {
      rawText: 'TJ HUMMUS 10OZ',
      parsedName: 'Hummus',
      qty: 1,
      unit: 'tub',
      unitPrice: 2.99,
      lineTotal: 2.99,
      category: 'snack',
      confidence: 0.88,
    },
    {
      rawText: 'TJ CHEESY POOFS 6OZ',
      parsedName: 'Cheese Puffs',
      qty: 1,
      unit: 'bag',
      unitPrice: 2.49,
      lineTotal: 2.49,
      category: 'snack',
      confidence: 0.81,
    },
    {
      rawText: 'TJ MANDARIN ORANGES',
      parsedName: 'Mandarin Oranges',
      qty: 1,
      unit: 'bag',
      unitPrice: 3.99,
      lineTotal: 3.99,
      category: 'fruit',
      confidence: 0.9,
    },
    {
      rawText: 'TJ STEELHEAD 6OZ',
      parsedName: 'Steelhead Trout',
      qty: 1,
      unit: 'pack',
      unitPrice: 7.99,
      lineTotal: 7.99,
      category: 'protein',
      confidence: 0.82,
    },
    {
      rawText: 'TJ MARINARA 24OZ',
      parsedName: 'Marinara Sauce',
      qty: 1,
      unit: 'jar',
      unitPrice: 2.29,
      lineTotal: 2.29,
      category: 'pantry',
      confidence: 0.89,
    },
    {
      rawText: 'TJ SPINACH ARTICHOKE DIP',
      parsedName: 'Spinach Artichoke Dip',
      qty: 1,
      unit: 'tub',
      unitPrice: 3.49,
      lineTotal: 3.49,
      category: 'snack',
      confidence: 0.86,
    },
    {
      rawText: 'TJ ORGANIC SPRING MIX',
      parsedName: 'Spring Mix',
      qty: 1,
      unit: 'bag',
      unitPrice: 2.49,
      lineTotal: 2.49,
      category: 'vegetable',
      confidence: 0.93,
    },
  ],
};

export const cornerStoreFixture: ParseResponse = {
  merchant: 'Corner Market',
  purchasedAt: null, // intentionally missing — exercises the null path
  currency: 'USD',
  lineItems: [
    {
      rawText: 'MILK 1/2 GAL',
      parsedName: 'Milk',
      qty: 1,
      unit: 'half-gal',
      unitPrice: 3.99,
      lineTotal: 3.99,
      category: 'dairy',
      confidence: 0.74,
    },
    {
      rawText: 'WHITE BREAD',
      parsedName: 'Bread',
      qty: 1,
      unit: 'loaf',
      unitPrice: 3.49,
      lineTotal: 3.49,
      category: 'carb',
      confidence: 0.62,
    },
    {
      rawText: 'COKE 2L',
      parsedName: 'Coke',
      qty: 1,
      unit: 'bottle',
      unitPrice: 2.79,
      lineTotal: 2.79,
      category: 'beverage',
      confidence: 0.81,
    },
    {
      rawText: 'CANDY BAR',
      parsedName: 'Candy Bar',
      qty: 1,
      unit: 'ea',
      unitPrice: 1.49,
      lineTotal: 1.49,
      category: 'snack',
      confidence: 0.45, // intentionally below default-accept threshold
    },
  ],
};

export const ALL_FIXTURES: Record<string, { fixture: ParseResponse; expectedLineCount: number }> = {
  wholeFoods: { fixture: wholeFoodsFixture, expectedLineCount: 8 },
  aldi: { fixture: aldiFixture, expectedLineCount: 6 },
  walmart: { fixture: walmartFixture, expectedLineCount: 10 },
  traderJoes: { fixture: traderJoesFixture, expectedLineCount: 7 },
  cornerStore: { fixture: cornerStoreFixture, expectedLineCount: 4 },
};
