-- =============================================================================
-- EatPal Stripe Products & Prices Configuration
-- =============================================================================
--
-- This file is a TEMPLATE. Replace the placeholder IDs with actual Stripe IDs
-- from your Stripe Dashboard or generated by the setup scripts:
--   - scripts/setup-stripe-products.ps1 (Windows PowerShell)
--   - scripts/setup-stripe-products.sh (Linux/macOS Bash)
--
-- Run this AFTER apply-stripe-columns.sql completes successfully
-- =============================================================================

-- =============================================================================
-- STEP 1: Ensure subscription_plans table has the correct pricing
-- =============================================================================
-- Update prices to match Stripe pricing (adjust as needed for your business)

UPDATE subscription_plans SET
    price_monthly = 14.99,
    price_yearly = 143.90  -- ~20% discount
WHERE name = 'Pro';

UPDATE subscription_plans SET
    price_monthly = 24.99,
    price_yearly = 239.90  -- ~20% discount
WHERE name = 'Family Plus';

UPDATE subscription_plans SET
    price_monthly = 99.00,
    price_yearly = 950.00  -- ~20% discount
WHERE name = 'Professional';

-- =============================================================================
-- STEP 2: Update Stripe IDs (REPLACE THESE WITH YOUR ACTUAL STRIPE IDs)
-- =============================================================================
-- Run the setup script to get new IDs, or use existing ones from Stripe Dashboard

-- Pro plan
UPDATE subscription_plans SET
    stripe_product_id = 'prod_REPLACE_WITH_YOUR_ID',
    stripe_price_id_monthly = 'price_REPLACE_WITH_YOUR_MONTHLY_ID',
    stripe_price_id_yearly = 'price_REPLACE_WITH_YOUR_YEARLY_ID'
WHERE name = 'Pro';

-- Family Plus plan
UPDATE subscription_plans SET
    stripe_product_id = 'prod_REPLACE_WITH_YOUR_ID',
    stripe_price_id_monthly = 'price_REPLACE_WITH_YOUR_MONTHLY_ID',
    stripe_price_id_yearly = 'price_REPLACE_WITH_YOUR_YEARLY_ID'
WHERE name = 'Family Plus';

-- Professional plan
UPDATE subscription_plans SET
    stripe_product_id = 'prod_REPLACE_WITH_YOUR_ID',
    stripe_price_id_monthly = 'price_REPLACE_WITH_YOUR_MONTHLY_ID',
    stripe_price_id_yearly = 'price_REPLACE_WITH_YOUR_YEARLY_ID'
WHERE name = 'Professional';

-- =============================================================================
-- STEP 3: Verify the updates
-- =============================================================================

SELECT
    name,
    stripe_product_id,
    stripe_price_id_monthly,
    stripe_price_id_yearly,
    price_monthly,
    price_yearly,
    is_active
FROM subscription_plans
WHERE name IN ('Free', 'Pro', 'Family Plus', 'Professional')
ORDER BY sort_order;

-- =============================================================================
-- Expected Results (with your actual Stripe IDs):
-- =============================================================================
-- name           | stripe_product_id | stripe_price_id_monthly | stripe_price_id_yearly | price_monthly | price_yearly | is_active
-- Free           | NULL              | NULL                    | NULL                   | 0.00          | 0.00         | true
-- Pro            | prod_xxx          | price_xxx               | price_xxx              | 14.99         | 143.90       | true
-- Family Plus    | prod_xxx          | price_xxx               | price_xxx              | 24.99         | 239.90       | true
-- Professional   | prod_xxx          | price_xxx               | price_xxx              | 99.00         | 950.00       | true
-- =============================================================================

-- =============================================================================
-- PRICING SUMMARY
-- =============================================================================
--
-- Plan           | Monthly  | Yearly (20% off) | Stripe Product Needed
-- ---------------|----------|------------------|----------------------
-- Free           | $0       | $0               | No (no Stripe)
-- Pro            | $14.99   | $143.90          | Yes
-- Family Plus    | $24.99   | $239.90          | Yes
-- Professional   | $99.00   | $950.00          | Yes
--
-- =============================================================================
-- STRIPE SETUP INSTRUCTIONS
-- =============================================================================
--
-- Option 1: Use the automated scripts
--   Windows: .\scripts\setup-stripe-products.ps1
--   Linux:   ./scripts/setup-stripe-products.sh
--
-- Option 2: Manual setup via Stripe Dashboard
--   1. Go to https://dashboard.stripe.com/products
--   2. Create 3 products: EatPal Pro, EatPal Family Plus, EatPal Professional
--   3. For each product, create 2 prices:
--      - Monthly recurring price
--      - Yearly recurring price
--   4. Copy the IDs and update this file
--
-- Option 3: Create via Stripe CLI manually
--   stripe products create --name="EatPal Pro" --description="For families with multiple children"
--   stripe prices create --product=prod_xxx --unit-amount=1499 --currency=usd --recurring[interval]=month
--   stripe prices create --product=prod_xxx --unit-amount=14390 --currency=usd --recurring[interval]=year
--
-- =============================================================================
