import { test, expect } from '@playwright/test';

/**
 * SEO Tests
 * Tests meta tags, structured data, and SEO best practices
 *
 * These assert against whatever `baseURL` the config points at. Run them
 * against the BUILT output, not the dev server:
 *
 *   npm run build && E2E_TARGET=dist npx playwright test tests/seo.spec.ts
 *
 * dist/ is what Cloudflare Pages serves and what a crawler reads. On the dev
 * server three of these fail for reasons that have nothing to do with SEO --
 * no h1 until React mounts, a stale <title> until Helmet applies, and
 * /sitemap.xml SPA-falling-back to HTML (it is generated by the
 * generate-sitemap edge function, not a static file).
 */

// All paths below are relative so `baseURL` decides the target.

test.describe('SEO & Meta Tags', () => {
  test('should have proper title tag on landing page', async ({ page }) => {
    await page.goto('/');
    const title = await page.title();
    expect(title).toBeTruthy();
    expect(title.length).toBeGreaterThan(10);
    expect(title.length).toBeLessThan(70);
  });

  test('should have meta description', async ({ page }) => {
    await page.goto('/');
    const description = await page.locator('meta[name="description"]').getAttribute('content');
    expect(description).toBeTruthy();
    expect(description!.length).toBeGreaterThan(50);
    expect(description!.length).toBeLessThan(160);
  });

  test('should have Open Graph tags', async ({ page }) => {
    await page.goto('/');

    const ogTitle = await page.locator('meta[property="og:title"]').getAttribute('content');
    const ogDescription = await page
      .locator('meta[property="og:description"]')
      .getAttribute('content');
    const ogImage = await page.locator('meta[property="og:image"]').getAttribute('content');

    expect(ogTitle).toBeTruthy();
    expect(ogDescription).toBeTruthy();
    if (ogImage) {
      expect(ogImage).toMatch(/^https?:\/\//);
    }
  });

  test('should have Twitter card tags', async ({ page }) => {
    await page.goto('/');

    const twitterCard = await page.locator('meta[name="twitter:card"]').getAttribute('content');
    expect(twitterCard).toBeTruthy();
  });

  test('should have canonical URL', async ({ page }) => {
    await page.goto('/');

    const canonical = await page.locator('link[rel="canonical"]').getAttribute('href');
    expect(canonical).toBeTruthy();
  });

  test('should have proper heading hierarchy', async ({ page }) => {
    await page.goto('/');

    // Retry rather than count once. On BOTH targets the first count is 0:
    // createRoot replaces the served markup (the prerendered snapshot included)
    // and React's own h1 does not exist until it renders. Counting immediately
    // measured that gap, not the page -- it reported 0 against dist even though
    // the served HTML carries the h1 a crawler reads. Settles to exactly 1 on
    // /, /pricing and /blog alike.
    await expect(page.locator('h1')).toHaveCount(1);
    expect(await page.locator('h1').textContent()).toBeTruthy();
  });

  test('should have alt text on images', async ({ page }) => {
    await page.goto('/');

    const imagesWithoutAlt = await page.locator('img:not([alt]), img[alt=""]').count();
    // Allow some decorative images without alt, but flag if too many
    expect(imagesWithoutAlt).toBeLessThan(10);
  });

  test('should have structured data (JSON-LD)', async ({ page }) => {
    await page.goto('/');

    const jsonLd = await page.locator('script[type="application/ld+json"]');
    if ((await jsonLd.count()) > 0) {
      const content = await jsonLd.first().textContent();
      expect(content).toBeTruthy();

      // Validate it's valid JSON
      expect(() => JSON.parse(content!)).not.toThrow();
    }
  });

  test('should have viewport meta tag', async ({ page }) => {
    await page.goto('/');

    const viewport = await page.locator('meta[name="viewport"]').getAttribute('content');
    expect(viewport).toContain('width=device-width');
  });

  test('should have favicon', async ({ page }) => {
    await page.goto('/');

    const favicon = page.locator('link[rel="icon"], link[rel="shortcut icon"]');
    expect(await favicon.count()).toBeGreaterThan(0);
  });

  test('should have proper language attribute', async ({ page }) => {
    await page.goto('/');

    const lang = await page.locator('html').getAttribute('lang');
    expect(lang).toBe('en');
  });

  test('should have robots meta tag or robots.txt', async ({ page }) => {
    const robotsResponse = await page.goto('/robots.txt');

    if (robotsResponse && robotsResponse.status() === 200) {
      const content = await robotsResponse.text();
      expect(content).toContain('User-agent');
    } else {
      // Check for robots meta tag instead
      await page.goto('/');
      const robotsMeta = await page.locator('meta[name="robots"]').count();
      expect(robotsMeta).toBeGreaterThanOrEqual(0);
    }
  });

  test('should have sitemap', async ({ page }) => {
    // /sitemap.xml is not a file. functions/sitemap.xml.ts is a Cloudflare Pages
    // Function that proxies the generate-sitemap edge function, so only a
    // Pages runtime answers this URL. Both local targets fall back to the SPA
    // shell and return 200 text/html, which the assertion below reads as "a
    // sitemap that is not XML" -- a false failure about the server, not the
    // site. `npx wrangler pages dev dist` (npm run pages:dev) is what covers it.
    test.skip(
      process.env.E2E_TARGET === 'dist',
      'served by a Pages Function; needs `wrangler pages dev`, not a static server'
    );

    const sitemapResponse = await page.goto('/sitemap.xml');

    if (sitemapResponse && sitemapResponse.status() === 200) {
      const content = await sitemapResponse.text();
      expect(content).toContain('urlset');
    }
  });

  test('should have unique titles on different pages', async ({ page }) => {
    await page.goto('/');
    const homeTitle = await page.title();
    expect(homeTitle).toBeTruthy();

    await page.goto('/pricing');
    // page.title() reads once. On the dev server react-helmet-async has not
    // applied the route's <title> yet at that moment, so the read returned the
    // homepage's and the test failed on a page whose title is in fact distinct.
    // Waiting for the title to stop being the previous one asserts what the
    // test means. Against dist the prerendered <title> is already correct and
    // this resolves on the first poll.
    await expect(page).not.toHaveTitle(homeTitle);
    expect(await page.title()).toBeTruthy();
  });
});
