import Foundation

struct GroceryItem: Identifiable, Codable, Equatable {
    let id: String
    var userId: String
    var householdId: String?
    var groceryListId: String?
    var name: String
    var category: String
    var quantity: Double
    var unit: String
    var checked: Bool
    var notes: String?
    var aisle: String?
    var photoUrl: String?
    var barcode: String?
    var brandPreference: String?
    var priority: String?
    var addedVia: String?
    var autoGenerated: Bool?
    /// US-243: optional per-unit price. Multiplied by `quantity` for the
    /// weekly grocery total. nil = unknown (skipped from forecast).
    var pricePerUnit: Double?
    /// US-243: ISO-4217 currency code paired with `pricePerUnit`.
    var currency: String?
    /// US-263: store-section taxonomy (`GroceryAisle.rawValue`). Drives
    /// section grouping in GroceryView and walk-order in ShoppingModeView.
    /// Independent of `category` — `category` stays as a `FoodCategory`
    /// for nutrition coloring, while `aisleSection` is the 32-value list.
    var aisleSection: String?
    /// US-285: Recipe this item was generated from (e.g. missing-ingredient
    /// bulk add). Lets the cross-module flows link a grocery item back to
    /// the recipe that triggered it — and lets "Mark made" auto-check the
    /// recipe-sourced grocery rows (US-262).
    /// Backed by `grocery_items.source_recipe_id` (migration 20251014…).
    /// Default of nil keeps the 17 existing memberwise-init call sites
    /// source-compatible without a sweeping rename.
    var sourceRecipeId: String? = nil
    var createdAt: String?
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case householdId = "household_id"
        case groceryListId = "grocery_list_id"
        case name, category, quantity, unit, checked, notes, aisle, barcode, priority
        case photoUrl = "photo_url"
        case brandPreference = "brand_preference"
        case addedVia = "added_via"
        case autoGenerated = "auto_generated"
        case pricePerUnit = "price_per_unit"
        case currency
        case aisleSection = "aisle_section"
        case sourceRecipeId = "source_recipe_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    mutating func apply(_ updates: GroceryItemUpdate) {
        if let name = updates.name { self.name = name }
        if let category = updates.category { self.category = category }
        if let quantity = updates.quantity { self.quantity = quantity }
        if let unit = updates.unit { self.unit = unit }
        if let checked = updates.checked { self.checked = checked }
        if let notes = updates.notes { self.notes = notes }
        if let aisle = updates.aisle { self.aisle = aisle }
        if let priority = updates.priority { self.priority = priority }
        if let pricePerUnit = updates.pricePerUnit { self.pricePerUnit = pricePerUnit }
        if let currency = updates.currency { self.currency = currency }
        if let aisleSection = updates.aisleSection { self.aisleSection = aisleSection }
    }

    /// US-263: typed accessor that returns the aisle section as the
    /// strongly-typed enum, or nil when the row predates the migration
    /// or holds an unknown value.
    var aisleSectionEnum: GroceryAisle? {
        guard let raw = aisleSection else { return nil }
        return GroceryAisle(rawValue: raw)
    }

    /// US-243: line-item total = price × quantity. Returns nil when price
    /// is unknown so callers can show "—" instead of "$0.00".
    var lineTotal: Double? {
        guard let price = pricePerUnit else { return nil }
        return price * quantity
    }
}

struct GroceryItemUpdate: Codable {
    var name: String?
    var category: String?
    var quantity: Double?
    var unit: String?
    var checked: Bool?
    var notes: String?
    var aisle: String?
    var priority: String?
    var pricePerUnit: Double?
    var currency: String?
    /// US-263: store-section taxonomy update.
    var aisleSection: String?

    enum CodingKeys: String, CodingKey {
        case name, category, quantity, unit, checked, notes, aisle, priority
        case pricePerUnit = "price_per_unit"
        case currency
        case aisleSection = "aisle_section"
    }
}

struct GroceryList: Identifiable, Codable, Equatable {
    let id: String
    var userId: String
    var householdId: String?
    var name: String
    var description: String?
    var icon: String?
    var color: String?
    var storeName: String?
    /// US-275: Optional FK into `store_layouts`. When set, the
    /// shopping/grocery views sort by that chain's aisle walk order
    /// instead of `GroceryAisle.storeWalkOrder`.
    var storeLayoutId: String?
    var isDefault: Bool?
    var isArchived: Bool?
    var createdAt: String?
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case householdId = "household_id"
        case name, description, icon, color
        case storeName = "store_name"
        case storeLayoutId = "store_layout_id"
        case isDefault = "is_default"
        case isArchived = "is_archived"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
