import Foundation

struct GroceryItem: Identifiable, Codable, Equatable {
    let id: String
    var userId: String
    var householdId: String?
    var groceryListId: String?
    var name: String
    var category: String
    var quantity: Double
    var unit: String
    var checked: Bool
    var notes: String?
    var aisle: String?
    var photoUrl: String?
    var barcode: String?
    var brandPreference: String?
    var priority: String?
    var addedVia: String?
    var autoGenerated: Bool?
    var createdAt: String?
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case householdId = "household_id"
        case groceryListId = "grocery_list_id"
        case name, category, quantity, unit, checked, notes, aisle, barcode, priority
        case photoUrl = "photo_url"
        case brandPreference = "brand_preference"
        case addedVia = "added_via"
        case autoGenerated = "auto_generated"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    mutating func apply(_ updates: GroceryItemUpdate) {
        if let name = updates.name { self.name = name }
        if let category = updates.category { self.category = category }
        if let quantity = updates.quantity { self.quantity = quantity }
        if let unit = updates.unit { self.unit = unit }
        if let checked = updates.checked { self.checked = checked }
        if let notes = updates.notes { self.notes = notes }
        if let aisle = updates.aisle { self.aisle = aisle }
        if let priority = updates.priority { self.priority = priority }
    }
}

struct GroceryItemUpdate: Codable {
    var name: String?
    var category: String?
    var quantity: Double?
    var unit: String?
    var checked: Bool?
    var notes: String?
    var aisle: String?
    var priority: String?

    enum CodingKeys: String, CodingKey {
        case name, category, quantity, unit, checked, notes, aisle, priority
    }
}

struct GroceryList: Identifiable, Codable, Equatable {
    let id: String
    var userId: String
    var householdId: String?
    var name: String
    var description: String?
    var icon: String?
    var color: String?
    var storeName: String?
    var isDefault: Bool?
    var isArchived: Bool?
    var createdAt: String?
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case householdId = "household_id"
        case name, description, icon, color
        case storeName = "store_name"
        case isDefault = "is_default"
        case isArchived = "is_archived"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
