/**
 * pSEO (Programmatic SEO) type definitions for EatPal.
 *
 * Phase 2: Page Type Definitions
 * Phase 3: JSON Schemas (TypeScript interfaces)
 *
 * These types drive the automated generation of ~1,500 food-chaining,
 * picky eater, and feeding challenge pages across 9 page types.
 */

// ─── DIMENSION ENUMS ────────────────────────────────────────────────────────────

export type SafeFoodSlug =
  // Tier 1 (22)
  | 'chicken-nuggets' | 'mac-and-cheese' | 'plain-pasta' | 'pizza'
  | 'grilled-cheese' | 'hot-dogs' | 'french-fries' | 'white-bread'
  | 'peanut-butter' | 'applesauce' | 'bananas' | 'cheese' | 'crackers'
  | 'yogurt' | 'scrambled-eggs' | 'pancakes' | 'quesadilla' | 'cereal'
  | 'apple-slices' | 'rice' | 'butter-noodles' | 'pb-and-j'
  // Tier 2 (18)
  | 'chicken-tenders' | 'meatballs' | 'corn' | 'carrots-raw' | 'cucumber'
  | 'string-cheese' | 'milk' | 'goldfish-crackers' | 'saltine-crackers'
  | 'plain-hamburger' | 'fish-sticks' | 'frozen-waffles' | 'oatmeal-plain'
  | 'plain-chicken-breast' | 'mashed-potatoes' | 'grapes' | 'strawberries' | 'watermelon'
  // Tier 3 (12)
  | 'plain-toast' | 'raisins' | 'pear' | 'mandarin-oranges' | 'plain-bagel'
  | 'cream-cheese' | 'hummus' | 'edamame' | 'plain-rice-cakes'
  | 'vanilla-ice-cream' | 'vanilla-pudding' | 'bread-rolls';

export type AgeGroupSlug = 'toddler' | 'preschooler' | 'early-elementary' | 'tween';

export type FeedingChallengeSlug =
  // Tier 1 (6)
  | 'texture-sensitivity' | 'limited-repertoire' | 'food-neophobia'
  | 'mealtime-battles' | 'arfid' | 'sensory-processing'
  // Tier 2 (4)
  | 'color-refusal' | 'brand-dependency' | 'food-jag' | 'mixed-foods-refusal';

export type MealOccasionSlug =
  // Tier 1 (4)
  | 'weeknight-dinner' | 'school-lunch' | 'breakfast' | 'snack'
  // Tier 2 (3)
  | 'holiday-meals' | 'restaurant' | 'birthday-party';

export type DietaryRestrictionSlug =
  | 'no-restrictions' | 'gluten-free' | 'dairy-free'
  | 'nut-free' | 'egg-free' | 'top8-free';

export type TaxonomyDimension =
  | 'safe_food' | 'age_group' | 'feeding_challenge'
  | 'meal_occasion' | 'dietary_restriction';

// ─── PAGE TYPES ─────────────────────────────────────────────────────────────────

export type PseoPageType =
  | 'FOOD_CHAINING_GUIDE'
  | 'FOOD_CHAINING_AGE_COMBO'
  | 'CHALLENGE_MEAL_OCCASION'
  | 'AGE_MEAL_OCCASION'
  | 'FOOD_CHALLENGE_COMBO'
  | 'FOOD_DIETARY_RESTRICTION'
  | 'CHALLENGE_LANDING'
  | 'AGE_GROUP_LANDING'
  | 'MEAL_OCCASION_LANDING';

export type PseoGenerationStatus =
  | 'pending'     // Not yet generated
  | 'generating'  // Currently being generated by AI
  | 'generated'   // Generated, awaiting validation
  | 'validated'   // Passed quality checks
  | 'published'   // Live on the site
  | 'failed'      // Generation or validation failed
  | 'archived';   // Removed from live site

export type SearchVolumeTier = 1 | 2 | 3;

// ─── TAXONOMY SEED INTERFACE ────────────────────────────────────────────────────

export interface TaxonomySeedItem {
  dimension: TaxonomyDimension;
  slug: string;
  display_name: string;
  tier: SearchVolumeTier;
  category?: string;
  sort_order: number;
  context?: Record<string, unknown>;
}

// ─── PAGE TYPE DEFINITION ───────────────────────────────────────────────────────

export interface PageTypeDefinition {
  pageTypeId: PseoPageType;
  displayName: string;
  urlPattern: string;
  titleTemplate: string;                       // DETERMINISTIC
  metaDescriptionTemplate: string;             // AI-FILL markers
  targetQueryPattern: string;
  searchVolumeTier: SearchVolumeTier;
  dataSources: string[];
  minimumDataThreshold: number;
  componentName: string;
  interactiveFeatures: string[];
  internalLinksTo: PseoPageType[];
  schemaMarkup: string[];                      // JSON-LD types
  freshnessSignal: { needsRefresh: boolean; intervalDays: number };
  usefulWithoutSearch: string;
}

// ─── PROMPT CONFIG ──────────────────────────────────────────────────────────────

export interface PseoPromptConfig {
  systemPrompt: string;
  contextTemplate: string;                     // {{placeholder}} syntax
  dataTemplate: string;                        // {{placeholder}} syntax
  schemaInstructions: string;
  outputRules: string[];
  qualityChecks: string[];
  bannedPhrases: string[];
}

// ─── DIMENSION COMBINATION ──────────────────────────────────────────────────────

export interface DimensionCombination {
  safe_food?: SafeFoodSlug;
  age_group?: AgeGroupSlug;
  feeding_challenge?: FeedingChallengeSlug;
  meal_occasion?: MealOccasionSlug;
  dietary_restriction?: DietaryRestrictionSlug;
}

// ---------------------------------------------------------------------------
// Shared content primitives
// ---------------------------------------------------------------------------

export interface PseoFaqItem {
  question: string;
  answer: string;
}

export interface PseoRelatedPage {
  title: string;
  slug: string;
  description: string;
}

export interface PseoBreadcrumb {
  label: string;
  href: string;
}

// ---------------------------------------------------------------------------
// Database row – mirrors the `pseo_pages` Supabase table
// ---------------------------------------------------------------------------

export interface PseoPageRow {
  id: string;
  slug: string;
  page_type: PseoPageType;
  generation_status: 'draft' | 'published' | 'archived';
  title: string;
  meta_description: string;
  canonical_url: string;
  breadcrumbs: PseoBreadcrumb[];
  content: PseoPageContent;
  related_pages: PseoRelatedPage[];
  created_at: string;
  updated_at: string;
}

/** Discriminated union: the shape of `content` depends on `page_type`. */
export type PseoPageContent =
  | FoodChainingGuideContent
  | FoodChainingAgeComboContent
  | ChallengeMealOccasionContent
  | AgeMealOccasionContent
  | FoodChallengeComboContent
  | FoodDietaryRestrictionContent
  | LandingPageContent;

// ---------------------------------------------------------------------------
// Page Type 1 – FOOD_CHAINING_GUIDE
// ---------------------------------------------------------------------------

export interface FoodChainStep {
  stage: string;
  description: string;
  foods: string[];
}

export interface IntroductionTechnique {
  step: number;
  title: string;
  description: string;
  timeline: string;
}

export interface FoodChainingGuideContent {
  _type: 'FOOD_CHAINING_GUIDE';
  headline: string;
  subheadline: string;
  intro: string;
  /** "Why [food] is a great starting point" section */
  validation: {
    heading: string;
    body: string;
    properties: string[];
  };
  /** Brief food chaining explainer */
  explainer: {
    heading: string;
    body: string;
  };
  /** 3-step progression */
  progression: FoodChainStep[];
  /** Shared sensory/flavor properties explanation */
  sharedProperties: {
    heading: string;
    body: string;
  };
  /** Step-by-step introduction techniques */
  techniques: IntroductionTechnique[];
  /** "What if it's refused?" */
  troubleshooting: {
    heading: string;
    body: string;
    tips: string[];
  };
  /** Progress tracking CTA */
  trackingCta: {
    heading: string;
    body: string;
  };
  faqs: PseoFaqItem[];
}

// ---------------------------------------------------------------------------
// Page Type 2 – FOOD_CHAINING_AGE_COMBO
// ---------------------------------------------------------------------------

export interface AgeSpecificTip {
  title: string;              // AI-FILL
  description: string;        // AI-FILL
  ageRelevance: string;       // AI-FILL - why this tip matters for this age
}

export interface FoodChainingAgeComboContent {
  _type: 'FOOD_CHAINING_AGE_COMBO';
  headline: string;                              // AI-FILL
  subheadline: string;                           // AI-FILL
  intro: string;                                 // AI-FILL - 2-3 sentences
  /** Age-specific context for this food */
  ageContext: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
    developmentalNote: string;                   // AI-FILL
  };
  /** 3-step progression (shared with base guide) */
  progression: FoodChainStep[];                  // FROM-DB + AI-FILL
  /** Age-specific introduction techniques */
  ageTechniques: AgeSpecificTip[];               // AI-FILL - 3-5 items
  /** Food play / try-bite activities for this age */
  activities: {
    heading: string;                             // AI-FILL
    items: { name: string; description: string }[];  // AI-FILL - 3-4 items
  };
  /** School/social implications */
  socialContext: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
  };
  faqs: PseoFaqItem[];                          // AI-FILL - exactly 4
}

// ---------------------------------------------------------------------------
// Page Type 3 – CHALLENGE_MEAL_OCCASION
// ---------------------------------------------------------------------------

export interface FoodIdeaCard {
  name: string;
  description: string;
  tags: string[];
}

export interface ParentScenario {
  situation: string;
  solution: string;
}

export interface ChallengeMealOccasionContent {
  _type: 'CHALLENGE_MEAL_OCCASION';
  headline: string;
  subheadline: string;
  intro: string;
  /** "Why [occasion] is hard for [challenge] kids" */
  whyHard: {
    heading: string;
    body: string;
  };
  /** Key principles grid */
  principles: {
    heading: string;
    items: { title: string; description: string }[];
  };
  /** Food ideas (25-30 items) */
  foodIdeas: {
    heading: string;
    items: FoodIdeaCard[];
  };
  /** What to avoid */
  avoid: {
    heading: string;
    items: string[];
  };
  /** Real parent scenario */
  scenario: ParentScenario;
  faqs: PseoFaqItem[];
}

// ---------------------------------------------------------------------------
// Page Type 4 – AGE_MEAL_OCCASION
// ---------------------------------------------------------------------------

export interface MealIdeaCard {
  name: string;
  description: string;
  tags: string[];
}

export interface SampleDayPlan {
  day: string;
  meals: { slot: string; item: string }[];
}

export interface AgeMealOccasionContent {
  _type: 'AGE_MEAL_OCCASION';
  headline: string;
  subheadline: string;
  intro: string;
  /** "Why [occasion] is hard at [age]" */
  whyHard: {
    heading: string;
    body: string;
  };
  /** One key principle highlight */
  keyPrinciple: {
    title: string;
    description: string;
  };
  /** Meal ideas (30-40 items) */
  mealIdeas: {
    heading: string;
    items: MealIdeaCard[];
  };
  /** 5-day sample plan */
  samplePlan: {
    heading: string;
    days: SampleDayPlan[];
  };
  /** Shopping list CTA */
  shoppingCta: {
    heading: string;
    body: string;
  };
  faqs: PseoFaqItem[];
}

// ---------------------------------------------------------------------------
// Page Type 5 – FOOD_CHALLENGE_COMBO
// ---------------------------------------------------------------------------

export interface ChallengeSpecificStrategy {
  title: string;              // AI-FILL
  description: string;        // AI-FILL
  steps: string[];            // AI-FILL - 2-4 steps
}

export interface FoodChallengeComboContent {
  _type: 'FOOD_CHALLENGE_COMBO';
  headline: string;                              // AI-FILL
  subheadline: string;                           // AI-FILL
  intro: string;                                 // AI-FILL - 2-3 sentences
  /** Why this food is relevant for this challenge */
  relevance: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
  };
  /** How the challenge affects food chaining from this food */
  challengeImpact: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
    considerations: string[];                    // AI-FILL - 3-5 items
  };
  /** Modified progression for this challenge */
  progression: FoodChainStep[];                  // FROM-DB + AI-FILL
  /** Challenge-specific strategies */
  strategies: ChallengeSpecificStrategy[];       // AI-FILL - 3-4 items
  /** When to seek professional help */
  professionalHelp: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
    signs: string[];                             // AI-FILL - 3-5 signs
  };
  faqs: PseoFaqItem[];                          // AI-FILL - exactly 4
}

// ---------------------------------------------------------------------------
// Page Type 6 – FOOD_DIETARY_RESTRICTION
// ---------------------------------------------------------------------------

export interface SafeBridgeFood {
  name: string;               // AI-FILL
  whySafe: string;            // AI-FILL - why it's safe for this restriction
  whereToBuy: string;         // AI-FILL - optional, include if helpful
}

export interface FoodDietaryRestrictionContent {
  _type: 'FOOD_DIETARY_RESTRICTION';
  headline: string;                              // AI-FILL
  subheadline: string;                           // AI-FILL
  intro: string;                                 // AI-FILL - 2-3 sentences
  /** Challenge of combining picky eating + restriction */
  dualChallenge: {
    heading: string;                             // AI-FILL
    body: string;                                // AI-FILL
  };
  /** Modified progression with restriction-safe foods only */
  progression: FoodChainStep[];                  // FROM-DB + AI-FILL
  /** Safe bridge foods for this restriction */
  safeBridgeFoods: SafeBridgeFood[];             // AI-FILL - 6-10 items
  /** Label reading tips for this restriction */
  labelReading: {
    heading: string;                             // AI-FILL
    tips: string[];                              // AI-FILL - 3-5 tips
  };
  /** Substitution guide */
  substitutions: {
    heading: string;                             // AI-FILL
    items: { original: string; substitute: string; notes: string }[];  // AI-FILL - 4-6
  };
  faqs: PseoFaqItem[];                          // AI-FILL - exactly 4
}

// ---------------------------------------------------------------------------
// Page Types 7, 8, 9 – Landing / Hub pages
// ---------------------------------------------------------------------------

export interface HubLink {
  title: string;
  slug: string;
  description: string;
}

export interface StatFact {
  value: string;
  label: string;
}

export interface LandingPageContent {
  _type: 'CHALLENGE_LANDING' | 'AGE_GROUP_LANDING' | 'MEAL_OCCASION_LANDING';
  headline: string;
  subheadline: string;
  intro: string;
  /** Overview prose */
  overview: {
    heading: string;
    body: string;
  };
  /** Hub links to child pages */
  hubLinks: HubLink[];
  /** Key stats or facts */
  stats: StatFact[];
  faqs: PseoFaqItem[];
}

// ---------------------------------------------------------------------------
// Supabase row – full pseo_pages table record
// ---------------------------------------------------------------------------

export interface PseoPageRecord {
  id: string;
  page_type: PseoPageType;
  slug: string;
  title: string;
  meta_description: string | null;
  safe_food_slug: SafeFoodSlug | null;
  age_group_slug: AgeGroupSlug | null;
  challenge_slug: FeedingChallengeSlug | null;
  meal_occasion_slug: MealOccasionSlug | null;
  dietary_restriction_slug: DietaryRestrictionSlug | null;
  content: PseoPageContent;
  canonical_url: string | null;
  schema_markup: Record<string, unknown> | null;
  keywords: string[] | null;
  generation_status: PseoGenerationStatus;
  generation_prompt_hash: string | null;
  generated_at: string | null;
  validated_at: string | null;
  published_at: string | null;
  generation_error: string | null;
  generation_model: string | null;
  generation_cost_cents: number;
  quality_score: number | null;
  word_count: number | null;
  internal_link_count: number | null;
  has_faq: boolean;
  has_schema_markup: boolean;
  freshness_days: number;
  last_refreshed_at: string | null;
  needs_refresh: boolean;
  tier: SearchVolumeTier;
  priority_score: number;
  created_at: string;
  updated_at: string;
}

export interface PseoGenerationQueueItem {
  id: string;
  page_type: PseoPageType;
  combination: DimensionCombination;
  priority: number;
  status: 'queued' | 'processing' | 'completed' | 'failed' | 'skipped';
  batch_id: string | null;
  attempt_count: number;
  max_attempts: number;
  error_message: string | null;
  created_at: string;
  processed_at: string | null;
  completed_at: string | null;
}

export interface PseoGenerationBatch {
  id: string;
  name: string;
  description: string | null;
  page_type: PseoPageType | null;
  total_pages: number;
  completed_pages: number;
  failed_pages: number;
  status: 'pending' | 'running' | 'completed' | 'paused' | 'failed';
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  created_by: string | null;
}

// ---------------------------------------------------------------------------
// Page Type Definitions constant (Phase 2)
// ---------------------------------------------------------------------------

export const PAGE_TYPE_DEFINITIONS: PageTypeDefinition[] = [
  {
    pageTypeId: 'FOOD_CHAINING_GUIDE',
    displayName: 'Food Chaining Guide',
    urlPattern: '/food-chaining/[safe-food]',
    titleTemplate: 'Food Chaining from [Food]: Step-by-Step Expansion Guide for Picky Eaters',
    metaDescriptionTemplate: 'Learn how to expand your picky eater\'s diet from [Food] using food chaining science. Step-by-step bridge foods, introduction techniques, and progress tracking.',
    targetQueryPattern: 'food chaining [food name]',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (safe_food)', 'foods table'],
    minimumDataThreshold: 3,
    componentName: 'FoodChainingGuide',
    interactiveFeatures: ['progression-table', 'checklist', 'copy-to-clipboard'],
    internalLinksTo: ['FOOD_CHAINING_AGE_COMBO', 'FOOD_CHALLENGE_COMBO', 'FOOD_DIETARY_RESTRICTION'],
    schemaMarkup: ['HowTo', 'ItemList'],
    freshnessSignal: { needsRefresh: true, intervalDays: 90 },
    usefulWithoutSearch: 'Parents can use this as a workbook to systematically expand from a specific safe food. The 3-step progression and bridge food list have standalone value even without finding it via search.',
  },
  {
    pageTypeId: 'FOOD_CHAINING_AGE_COMBO',
    displayName: 'Food Chaining + Age Guide',
    urlPattern: '/food-chaining/[safe-food]/[age-group]',
    titleTemplate: 'Food Chaining from [Food] for [Age Group]s: Age-Specific Tips',
    metaDescriptionTemplate: 'Age-specific food chaining guide for [age group]s starting from [Food]. Developmental tips, activities, and techniques designed for [age range].',
    targetQueryPattern: '[age group] picky eater food chaining [food]',
    searchVolumeTier: 2,
    dataSources: ['pseo_taxonomy (safe_food, age_group)', 'foods table'],
    minimumDataThreshold: 3,
    componentName: 'FoodChainingGuide',
    interactiveFeatures: ['progression-table', 'age-activities'],
    internalLinksTo: ['FOOD_CHAINING_GUIDE', 'AGE_MEAL_OCCASION', 'AGE_GROUP_LANDING'],
    schemaMarkup: ['HowTo'],
    freshnessSignal: { needsRefresh: true, intervalDays: 120 },
    usefulWithoutSearch: 'Provides developmentally appropriate food introduction techniques. A parent of a 3-year-old needs different strategies than a parent of a 10-year-old.',
  },
  {
    pageTypeId: 'CHALLENGE_MEAL_OCCASION',
    displayName: 'Challenge + Meal Occasion Guide',
    urlPattern: '/[challenge]/[meal-occasion]',
    titleTemplate: '[Meal Occasion] Ideas for [Challenge Type] Kids: Options That Work',
    metaDescriptionTemplate: 'Practical [meal occasion] ideas specifically designed for kids with [challenge type]. Includes food lists, tips, and real parent scenarios.',
    targetQueryPattern: '[meal occasion] ideas for [challenge] picky eater',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (feeding_challenge, meal_occasion)', 'foods table'],
    minimumDataThreshold: 6,
    componentName: 'ChallengeMealOccasion',
    interactiveFeatures: ['food-grid', 'filtering', 'copy-to-clipboard'],
    internalLinksTo: ['CHALLENGE_LANDING', 'MEAL_OCCASION_LANDING', 'FOOD_CHAINING_GUIDE'],
    schemaMarkup: ['ItemList', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 60 },
    usefulWithoutSearch: 'A parent dealing with texture sensitivity at school lunch can print this page and use the food ideas list directly. The scenario section provides immediately actionable advice.',
  },
  {
    pageTypeId: 'AGE_MEAL_OCCASION',
    displayName: 'Age + Meal Occasion Guide',
    urlPattern: '/[age-group]/[meal-occasion]-ideas',
    titleTemplate: '[Meal Occasion] Ideas for [Age Group] Picky Eaters (That Actually Work)',
    metaDescriptionTemplate: 'Proven [meal occasion] ideas for [age group] picky eaters. Includes [N]+ food ideas, a 5-day sample plan, and shopping list.',
    targetQueryPattern: '[meal occasion] ideas for [age group] picky eater',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (age_group, meal_occasion)', 'foods table', 'recipes table'],
    minimumDataThreshold: 10,
    componentName: 'AgeMealOccasion',
    interactiveFeatures: ['food-grid', 'sample-plan', 'shopping-list-cta'],
    internalLinksTo: ['AGE_GROUP_LANDING', 'MEAL_OCCASION_LANDING', 'FOOD_CHAINING_GUIDE'],
    schemaMarkup: ['ItemList', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 60 },
    usefulWithoutSearch: 'The 5-day sample plan and 30+ food ideas make this a printable meal planning resource. Parents can bookmark and reference weekly.',
  },
  {
    pageTypeId: 'FOOD_CHALLENGE_COMBO',
    displayName: 'Food + Challenge Guide',
    urlPattern: '/food-chaining/[safe-food]/[challenge]',
    titleTemplate: 'Food Chaining from [Food] for Kids with [Challenge]: A Parent\'s Guide',
    metaDescriptionTemplate: 'How to use food chaining from [Food] when your child has [challenge type]. Modified progression, challenge-specific strategies, and when to seek help.',
    targetQueryPattern: 'food chaining [food] [challenge type]',
    searchVolumeTier: 2,
    dataSources: ['pseo_taxonomy (safe_food, feeding_challenge)', 'foods table'],
    minimumDataThreshold: 3,
    componentName: 'FoodChainingGuide',
    interactiveFeatures: ['progression-table', 'strategy-cards'],
    internalLinksTo: ['FOOD_CHAINING_GUIDE', 'CHALLENGE_LANDING', 'CHALLENGE_MEAL_OCCASION'],
    schemaMarkup: ['HowTo', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 120 },
    usefulWithoutSearch: 'Parents of a child with ARFID who eats chicken nuggets need a different progression than a typical picky eater. This page provides that challenge-specific guidance.',
  },
  {
    pageTypeId: 'FOOD_DIETARY_RESTRICTION',
    displayName: 'Food + Dietary Restriction Guide',
    urlPattern: '/[dietary-restriction]/food-chaining/[safe-food]',
    titleTemplate: '[Dietary Restriction] Food Chaining from [Food]: Safe Bridge Foods',
    metaDescriptionTemplate: '[Dietary restriction] food chaining guide from [Food]. All bridge foods verified safe. Includes substitutions, label reading tips, and restriction-safe progression.',
    targetQueryPattern: '[dietary restriction] picky eater food chaining [food]',
    searchVolumeTier: 2,
    dataSources: ['pseo_taxonomy (safe_food, dietary_restriction)', 'foods table'],
    minimumDataThreshold: 3,
    componentName: 'FoodChainingGuide',
    interactiveFeatures: ['progression-table', 'substitution-table', 'label-tips'],
    internalLinksTo: ['FOOD_CHAINING_GUIDE', 'CHALLENGE_MEAL_OCCASION'],
    schemaMarkup: ['ItemList', 'HowTo'],
    freshnessSignal: { needsRefresh: true, intervalDays: 90 },
    usefulWithoutSearch: 'A picky eater with celiac disease has double the challenge. This page provides verified safe bridge foods — a resource that barely exists online.',
  },
  {
    pageTypeId: 'CHALLENGE_LANDING',
    displayName: 'Challenge Type Landing Page',
    urlPattern: '/guides/[challenge]',
    titleTemplate: '[Challenge Type] in Children: Complete Parent\'s Guide to Picky Eating',
    metaDescriptionTemplate: 'Everything parents need to know about [challenge type] in children. Causes, signs, food chaining strategies, and when to see a feeding therapist.',
    targetQueryPattern: '[challenge type] children picky eating',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (feeding_challenge)', 'pseo_pages (child pages)'],
    minimumDataThreshold: 1,
    componentName: 'LandingPage',
    interactiveFeatures: ['hub-links', 'stats-grid'],
    internalLinksTo: ['CHALLENGE_MEAL_OCCASION', 'FOOD_CHALLENGE_COMBO'],
    schemaMarkup: ['MedicalWebPage', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 180 },
    usefulWithoutSearch: 'Hub page that gives parents a complete overview of a specific feeding challenge and links to all relevant content. Serves as an entry point to EatPal\'s authority on the topic.',
  },
  {
    pageTypeId: 'AGE_GROUP_LANDING',
    displayName: 'Age Group Landing Page',
    urlPattern: '/guides/[age-group]-picky-eater',
    titleTemplate: 'Picky Eating in [Age Group]s: What to Know and What to Do',
    metaDescriptionTemplate: 'Guide for parents of picky [age group]s. Age-specific causes, strategies, and meal ideas. Know when it\'s normal and when to seek help.',
    targetQueryPattern: '[age group] picky eater help',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (age_group)', 'pseo_pages (child pages)'],
    minimumDataThreshold: 1,
    componentName: 'LandingPage',
    interactiveFeatures: ['hub-links', 'stats-grid'],
    internalLinksTo: ['AGE_MEAL_OCCASION', 'FOOD_CHAINING_AGE_COMBO'],
    schemaMarkup: ['MedicalWebPage', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 180 },
    usefulWithoutSearch: 'Parents searching by their child\'s age get a comprehensive overview of picky eating at that developmental stage, with links to all relevant meal plans and food chaining guides.',
  },
  {
    pageTypeId: 'MEAL_OCCASION_LANDING',
    displayName: 'Meal Occasion Landing Page',
    urlPattern: '/guides/[meal-occasion]-picky-eater',
    titleTemplate: '[Meal Occasion] for Picky Eaters: Ideas, Strategies & Meal Plans',
    metaDescriptionTemplate: 'Complete guide to [meal occasion] for picky eaters. Ideas by age, challenge type, and dietary restriction. Sample plans and shopping lists.',
    targetQueryPattern: '[meal occasion] picky eater ideas',
    searchVolumeTier: 1,
    dataSources: ['pseo_taxonomy (meal_occasion)', 'pseo_pages (child pages)'],
    minimumDataThreshold: 1,
    componentName: 'LandingPage',
    interactiveFeatures: ['hub-links', 'stats-grid'],
    internalLinksTo: ['CHALLENGE_MEAL_OCCASION', 'AGE_MEAL_OCCASION'],
    schemaMarkup: ['ItemList', 'FAQPage'],
    freshnessSignal: { needsRefresh: true, intervalDays: 90 },
    usefulWithoutSearch: 'The "school lunch for picky eaters" page, for example, links to all challenge-specific and age-specific lunch pages, creating a comprehensive hub parents can explore.',
  },
];
