package com.eatpal.app.models

import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Round-trips the 5 database-critical models against known-good JSON snippets
 * captured from the iOS encoder. Guards the load-bearing snake_case wire
 * contract (see CLAUDE.md) — if iOS renames a column we break a test here
 * rather than silently diverging in production.
 */
class ModelsSerializationTest {

    private val json = Json { ignoreUnknownKeys = true; explicitNulls = false }

    @Test
    fun `Food round-trips snake_case`() {
        val source = """
            {"id":"f1","user_id":"u1","name":"Milk","category":"dairy",
             "is_safe":true,"is_try_bite":false,"allergens":["lactose"]}
        """.trimIndent()
        val food: Food = json.decodeFromString(source)
        assertEquals("f1", food.id)
        assertEquals("u1", food.userId)
        assertEquals(true, food.isSafe)
        assertEquals(false, food.isTryBite)
        assertEquals(listOf("lactose"), food.allergens)

        // encodeDefaults = false (stdlib default) skips fields whose value matches
        // the declared default, so we only assert fields that DON'T have defaults.
        val encoded = Json { encodeDefaults = true }.encodeToString(Food.serializer(), food)
        assertTrue("should emit user_id", encoded.contains("\"user_id\""))
        assertTrue("should emit is_safe", encoded.contains("\"is_safe\""))
        assertTrue("should emit is_try_bite", encoded.contains("\"is_try_bite\""))
    }

    @Test
    fun `Recipe snake_case covers food_ids + prep_time`() {
        val source = """
            {"id":"r1","user_id":"u1","name":"Pasta",
             "food_ids":["f1","f2"],"prep_time":"10 min","cook_time":"15 min",
             "kid_friendly_score":0.8,"nutrition_info":{"protein_g":12.5}}
        """.trimIndent()
        val recipe: Recipe = json.decodeFromString(source)
        assertEquals(listOf("f1", "f2"), recipe.foodIds)
        assertEquals("10 min", recipe.prepTime)
        assertEquals(0.8, recipe.kidFriendlyScore!!, 0.0001)
        assertEquals(12.5, recipe.nutritionInfo?.proteinG!!, 0.0001)
    }

    @Test
    fun `PlanEntry meal_slot + food_id + kid_id`() {
        val source = """
            {"id":"p1","user_id":"u1","kid_id":"k1","date":"2026-04-21",
             "meal_slot":"dinner","food_id":"f1","recipe_id":"r1","result":"ate"}
        """.trimIndent()
        val entry: PlanEntry = json.decodeFromString(source)
        assertEquals("k1", entry.kidId)
        assertEquals("dinner", entry.mealSlot)
        assertEquals("r1", entry.recipeId)
        assertEquals("ate", entry.result)
    }

    @Test
    fun `GroceryItem added_via + grocery_list_id`() {
        val source = """
            {"id":"g1","user_id":"u1","name":"Apples","category":"fruit",
             "quantity":3.0,"unit":"ea","checked":false,
             "grocery_list_id":"list-1","added_via":"text_import","auto_generated":false}
        """.trimIndent()
        val item: GroceryItem = json.decodeFromString(source)
        assertEquals("list-1", item.groceryListId)
        assertEquals("text_import", item.addedVia)
        assertEquals(false, item.autoGenerated)
    }

    @Test
    fun `Kid covers texture + flavor + strategy lists`() {
        val source = """
            {"id":"k1","user_id":"u1","name":"Alex","age":7,
             "texture_preferences":["crunchy"],"flavor_preferences":["salty"],
             "helpful_strategies":["plate colors"],"pickiness_level":"high"}
        """.trimIndent()
        val kid: Kid = json.decodeFromString(source)
        assertEquals("Alex", kid.name)
        assertEquals(7, kid.age)
        assertEquals(listOf("crunchy"), kid.texturePreferences)
        assertEquals(listOf("salty"), kid.flavorPreferences)
        assertEquals(listOf("plate colors"), kid.helpfulStrategies)
    }

    @Test
    fun `FoodUpdate only emits set fields`() {
        val update = FoodUpdate(name = "New name")
        val encoded = json.encodeToString(FoodUpdate.serializer(), update)
        assertTrue(encoded.contains("\"name\":\"New name\""))
        assertTrue("should not emit null fields with explicitNulls=false", !encoded.contains("null"))
    }
}
