package com.eatpal.app.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Mirrors iOS `GroceryItem`. */
@Serializable
data class GroceryItem(
    val id: String,
    @SerialName("user_id") val userId: String,
    @SerialName("household_id") val householdId: String? = null,
    @SerialName("grocery_list_id") val groceryListId: String? = null,
    val name: String,
    val category: String,
    val quantity: Double,
    val unit: String,
    val checked: Boolean = false,
    val notes: String? = null,
    val aisle: String? = null,
    @SerialName("photo_url") val photoUrl: String? = null,
    val barcode: String? = null,
    @SerialName("brand_preference") val brandPreference: String? = null,
    val priority: String? = null,
    @SerialName("added_via") val addedVia: String? = null,
    @SerialName("auto_generated") val autoGenerated: Boolean? = null,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
) {
    fun applying(u: GroceryItemUpdate): GroceryItem = copy(
        name = u.name ?: name,
        category = u.category ?: category,
        quantity = u.quantity ?: quantity,
        unit = u.unit ?: unit,
        checked = u.checked ?: checked,
        notes = u.notes ?: notes,
        aisle = u.aisle ?: aisle,
        priority = u.priority ?: priority,
    )
}

@Serializable
data class GroceryItemUpdate(
    val name: String? = null,
    val category: String? = null,
    val quantity: Double? = null,
    val unit: String? = null,
    val checked: Boolean? = null,
    val notes: String? = null,
    val aisle: String? = null,
    val priority: String? = null,
)

@Serializable
data class GroceryList(
    val id: String,
    @SerialName("user_id") val userId: String,
    @SerialName("household_id") val householdId: String? = null,
    val name: String,
    val description: String? = null,
    val icon: String? = null,
    val color: String? = null,
    @SerialName("store_name") val storeName: String? = null,
    @SerialName("is_default") val isDefault: Boolean? = null,
    @SerialName("is_archived") val isArchived: Boolean? = null,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
)
