import Foundation

/// Generates grocery list items from meal plan entries and recipes.
///
/// US-264: walks plan entries directly so we can preserve which recipe
/// + plan entry contributed to each grocery item. The result carries
/// both the new grocery items and the `grocery_item_sources` rows that
/// link them back to their meals — together they power the "By Recipe"
/// view in `GroceryView`.
@MainActor
enum GroceryGeneratorService {

    /// Output bundle from a generation run. `items` and `sources` are
    /// inserted together by `addGeneratedItems(_:appState:)` so the link
    /// rows always have parent grocery items to point at.
    struct Result {
        var items: [GroceryItem]
        var sources: [GroceryItemSource]
    }

    /// Generates grocery items + per-recipe source rows from a week's
    /// meal plan entries. Items already on the grocery list (matched by
    /// lowercased name) are skipped — but their planned occurrences are
    /// still tagged with sources so the "By Recipe" view shows them
    /// under the right recipes after the user re-checks them.
    static func generateFromMealPlan(
        weekStart: Date,
        kidIds: [String],
        appState: AppState
    ) async throws -> Result {
        let calendar = Calendar.current
        let dates = (0..<7).map { offset in
            calendar.date(byAdding: .day, value: offset, to: weekStart)!
        }

        // Build a candidate-per-name map. Each candidate accumulates the
        // contributions (one per plan entry / recipe ingredient) so we can
        // emit source rows for each one after dedupe.
        var candidates: [String: Candidate] = [:]

        for date in dates {
            let dateString = date.isoDateString
            for kidId in kidIds {
                let entries = appState.planEntriesForDate(date, kidId: kidId)
                for entry in entries {
                    accumulate(
                        from: entry,
                        dateString: dateString,
                        appState: appState,
                        into: &candidates
                    )
                }
            }
        }

        // Convert candidates to grocery items + source rows. Skip
        // candidates whose name already exists on the list — but DO emit
        // source rows for those existing items so the "By Recipe" view
        // can show them under the right recipe sections.
        let existingByName = Dictionary(
            uniqueKeysWithValues: appState.groceryItems.map {
                ($0.name.lowercased(), $0.id)
            }
        )

        var items: [GroceryItem] = []
        var sources: [GroceryItemSource] = []

        for (nameKey, candidate) in candidates {
            let groceryItemId: String
            let isNew: Bool
            if let existingId = existingByName[nameKey] {
                groceryItemId = existingId
                isNew = false
            } else {
                let newId = UUID().uuidString
                groceryItemId = newId
                isNew = true
                items.append(GroceryItem(
                    id: newId,
                    userId: "",
                    name: candidate.displayName,
                    category: candidate.category,
                    quantity: candidate.totalQuantity,
                    unit: candidate.unit,
                    checked: false,
                    aisle: candidate.aisleHint,
                    autoGenerated: true,
                    aisleSection: candidate.aisle.rawValue
                ))
            }

            for contribution in candidate.contributions {
                sources.append(GroceryItemSource.new(
                    groceryItemId: groceryItemId,
                    recipeId: contribution.recipeId,
                    planEntryId: contribution.planEntryId,
                    mealDate: contribution.mealDate,
                    mealSlot: contribution.mealSlot,
                    contributedQuantity: contribution.quantity
                ))
            }
            _ = isNew
        }

        return Result(
            items: items.sorted { $0.category < $1.category },
            sources: sources
        )
    }

    /// Persist the generation Result. Items go in first so the source
    /// FK is satisfiable; sources follow in a single bulk insert.
    static func addGeneratedItems(
        _ result: Result,
        appState: AppState
    ) async throws {
        for item in result.items {
            try await appState.addGroceryItem(item)
        }

        if !result.sources.isEmpty {
            try await DataService.shared.insertGroceryItemSources(result.sources)
            // Mirror the new rows into the in-memory array so the
            // "By Recipe" view reflects them without a full reload.
            await MainActor.run {
                appState.groceryItemSources.append(contentsOf: result.sources)
            }
        }

        let toast = ToastManager.shared
        let count = result.items.count
        if count > 0 {
            toast.success(
                "Grocery list updated",
                message: "Added \(count) items from meal plan."
            )
        } else if !result.sources.isEmpty {
            toast.info(
                "Linked existing items",
                message: "Tagged \(result.sources.count) recipe links to your list."
            )
        }
        HapticManager.success()
    }

    // MARK: - Candidate accumulation

    /// One in-progress grocery item being built. Many plan entries / many
    /// recipe ingredient rows can fold into a single candidate (chicken
    /// from Mon dinner + Wed lunch = one grocery item, two contributions).
    private struct Candidate {
        var displayName: String
        var category: String
        var unit: String
        var totalQuantity: Double
        var aisleHint: String?
        var aisle: GroceryAisle
        var contributions: [Contribution]
    }

    private struct Contribution {
        var recipeId: String?
        var planEntryId: String?
        var mealDate: String?
        var mealSlot: String?
        var quantity: Double?
    }

    /// Walk a single plan entry and add every ingredient it contributes
    /// to the candidates map. Order of preference for ingredient source:
    ///   1. structured `recipe.ingredients` (US-265) — best signal
    ///   2. linked `recipe.foodIds` resolved against pantry foods
    ///   3. legacy `recipe.additional_ingredients` comma string
    ///   4. direct foodId on the plan entry (recipe-less meal)
    private static func accumulate(
        from entry: PlanEntry,
        dateString: String,
        appState: AppState,
        into candidates: inout [String: Candidate]
    ) {
        let recipe = entry.recipeId.flatMap { rid in
            appState.recipes.first(where: { $0.id == rid })
        }

        if let recipe {
            if !recipe.ingredients.isEmpty {
                for ing in recipe.ingredients {
                    addStructuredIngredient(
                        ing,
                        recipe: recipe,
                        entry: entry,
                        dateString: dateString,
                        appState: appState,
                        into: &candidates
                    )
                }
            } else {
                // No structured rows yet — fall through to legacy paths.
                for foodId in recipe.foodIds {
                    addFoodContribution(
                        foodId: foodId,
                        recipe: recipe,
                        entry: entry,
                        dateString: dateString,
                        appState: appState,
                        into: &candidates
                    )
                }
                if let extras = recipe.additionalIngredients, !extras.isEmpty {
                    let names = extras.split(separator: ",").map {
                        $0.trimmingCharacters(in: .whitespaces)
                    }
                    for name in names where !name.isEmpty {
                        addLegacyName(
                            name,
                            recipe: recipe,
                            entry: entry,
                            dateString: dateString,
                            into: &candidates
                        )
                    }
                }
            }
        } else {
            // Recipe-less meal: the foodId on the entry IS the meal.
            addFoodContribution(
                foodId: entry.foodId,
                recipe: nil,
                entry: entry,
                dateString: dateString,
                appState: appState,
                into: &candidates
            )
        }
    }

    private static func addStructuredIngredient(
        _ ing: RecipeIngredient,
        recipe: Recipe,
        entry: PlanEntry,
        dateString: String,
        appState: AppState,
        into candidates: inout [String: Candidate]
    ) {
        let trimmed = ing.name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        // Defensive reparse: rows imported before US-265's name/qty/unit
        // split landed the whole raw string ("4 tablespoons vegetable
        // oil") in `name` with nil qty/unit. Running them through the
        // parser idempotently cleans the display name and recovers the
        // quantity + unit on the way to the grocery list.
        let parsed = IngredientTextParser.parse(trimmed)
        let displayName = parsed.name
        let resolvedQty = ing.quantity ?? parsed.quantity
        let resolvedUnit = ing.unit ?? parsed.unit

        let key = displayName.lowercased()
        let linkedFood = ing.foodId.flatMap { fid in
            appState.foods.first(where: { $0.id == fid })
        }
        let category = linkedFood?.category ?? "other"
        // Prefer the linked food's category mapping; fall back to a
        // name-keyword classifier so unlinked ingredients still land in
        // a real aisle instead of one giant "Other" bucket.
        let aisle: GroceryAisle = {
            if linkedFood != nil {
                return GroceryAisle.fromLegacyCategory(category)
            }
            return GroceryAisle.classify(displayName)
        }()

        var existing = candidates[key] ?? Candidate(
            displayName: displayName,
            category: category,
            unit: resolvedUnit ?? "",
            totalQuantity: 0,
            aisleHint: linkedFood?.aisle,
            aisle: aisle,
            contributions: []
        )
        let qty = resolvedQty ?? 1
        existing.totalQuantity += qty
        if existing.unit.isEmpty, let unit = resolvedUnit { existing.unit = unit }
        existing.contributions.append(Contribution(
            recipeId: recipe.id,
            planEntryId: entry.id,
            mealDate: dateString,
            mealSlot: entry.mealSlot,
            quantity: resolvedQty
        ))
        candidates[key] = existing
    }

    private static func addFoodContribution(
        foodId: String,
        recipe: Recipe?,
        entry: PlanEntry,
        dateString: String,
        appState: AppState,
        into candidates: inout [String: Candidate]
    ) {
        guard let food = appState.foods.first(where: { $0.id == foodId }) else { return }
        let key = food.name.lowercased()
        let aisle = GroceryAisle.fromLegacyCategory(food.category)
        var existing = candidates[key] ?? Candidate(
            displayName: food.name,
            category: food.category,
            unit: food.unit ?? "servings",
            totalQuantity: 0,
            aisleHint: food.aisle,
            aisle: aisle,
            contributions: []
        )
        existing.totalQuantity += 1
        existing.contributions.append(Contribution(
            recipeId: recipe?.id,
            planEntryId: entry.id,
            mealDate: dateString,
            mealSlot: entry.mealSlot,
            quantity: 1
        ))
        candidates[key] = existing
    }

    private static func addLegacyName(
        _ name: String,
        recipe: Recipe,
        entry: PlanEntry,
        dateString: String,
        into candidates: inout [String: Candidate]
    ) {
        // Same parse + classify path as the structured side so legacy
        // recipes (those still serving from `recipe.additional_ingredients`)
        // produce clean display names + aisles too.
        let parsed = IngredientTextParser.parse(name)
        let displayName = parsed.name
        let key = displayName.lowercased()
        let aisle = GroceryAisle.classify(displayName)
        var existing = candidates[key] ?? Candidate(
            displayName: displayName,
            category: "other",
            unit: parsed.unit ?? "",
            totalQuantity: 0,
            aisleHint: nil,
            aisle: aisle,
            contributions: []
        )
        existing.totalQuantity += parsed.quantity ?? 1
        existing.contributions.append(Contribution(
            recipeId: recipe.id,
            planEntryId: entry.id,
            mealDate: dateString,
            mealSlot: entry.mealSlot,
            quantity: parsed.quantity
        ))
        candidates[key] = existing
    }
}

