import Foundation

/// Generates grocery list items from meal plan entries and recipes.
enum GroceryGeneratorService {
    /// Generates grocery items from a week's meal plan entries.
    /// Cross-references recipes to extract ingredients, and deduplicates.
    @MainActor
    static func generateFromMealPlan(
        weekStart: Date,
        kidIds: [String],
        appState: AppState
    ) async throws -> [GroceryItem] {
        let calendar = Calendar.current
        let dates = (0..<7).map { offset in
            calendar.date(byAdding: .day, value: offset, to: weekStart)!
        }

        // Collect all food IDs from plan entries for the week
        var foodIdCounts: [String: Int] = [:]
        for date in dates {
            for kidId in kidIds {
                let entries = appState.planEntriesForDate(date, kidId: kidId)
                for entry in entries {
                    foodIdCounts[entry.foodId, default: 0] += 1
                }
            }
        }

        // Build grocery items from foods, deduplicating
        var groceryItems: [GroceryItem] = []
        let existingNames = Set(appState.groceryItems.map { $0.name.lowercased() })

        for (foodId, count) in foodIdCounts {
            guard let food = appState.foods.first(where: { $0.id == foodId }) else { continue }

            // Skip if already on grocery list
            if existingNames.contains(food.name.lowercased()) { continue }

            let item = GroceryItem(
                id: UUID().uuidString,
                userId: "",
                name: food.name,
                category: food.category,
                quantity: Double(count),
                unit: food.unit ?? "servings",
                checked: false,
                aisle: food.aisle,
                autoGenerated: true,
                // US-263: best-effort aisle assignment from the food's
                // FoodCategory. US-266 will refine with name-based lookup
                // for items where the category alone can't pinpoint the
                // store section (e.g. "snack" -> snacks vs candy vs crackers).
                aisleSection: aisleFromFoodCategory(food.category).rawValue
            )

            groceryItems.append(item)
        }

        // Also check recipes for additional ingredients
        let recipeIds = Set(appState.planEntries.compactMap(\.recipeId))
        for recipe in appState.recipes where recipeIds.contains(recipe.id) {
            if let ingredientsStr = recipe.additionalIngredients, !ingredientsStr.isEmpty {
                let ingredients = ingredientsStr.split(separator: ",").map {
                    $0.trimmingCharacters(in: .whitespaces)
                }
                for ingredient in ingredients {
                    let ingredientLower = ingredient.lowercased()
                    if !existingNames.contains(ingredientLower) &&
                       !groceryItems.contains(where: { $0.name.lowercased() == ingredientLower }) {
                        groceryItems.append(GroceryItem(
                            id: UUID().uuidString,
                            userId: "",
                            name: ingredient,
                            category: "other",
                            quantity: 1,
                            unit: "",
                            checked: false,
                            autoGenerated: true,
                            // US-263: unstructured recipe extras have no
                            // FoodCategory hint, so default to .other —
                            // US-266 classifier will refine on first sync.
                            aisleSection: GroceryAisle.other.rawValue
                        ))
                    }
                }
            }
        }

        return groceryItems.sorted { $0.category < $1.category }
    }

    /// US-263: best-effort mapping from the legacy 6-bucket FoodCategory
    /// to the 32-aisle taxonomy. Used when generating from meal plan
    /// foods where we don't yet have item-level classification.
    private static func aisleFromFoodCategory(_ raw: String) -> GroceryAisle {
        switch FoodCategory(rawValue: raw) {
        case .protein:   return .meatDeli
        case .carb:      return .pasta
        case .dairy:     return .dairy
        case .fruit:     return .produce
        case .vegetable: return .produce
        case .snack:     return .snacks
        case .none:      return .other
        }
    }

    /// Adds all generated items to the grocery list via AppState.
    @MainActor
    static func addGeneratedItems(
        _ items: [GroceryItem],
        appState: AppState
    ) async throws {
        for item in items {
            try await appState.addGroceryItem(item)
        }

        let toast = ToastManager.shared
        toast.success("Grocery list updated", message: "Added \(items.count) items from meal plan.")
        HapticManager.success()
    }
}
