import Foundation

/// Generates grocery list items from meal plan entries and recipes.
enum GroceryGeneratorService {
    /// Generates grocery items from a week's meal plan entries.
    /// Cross-references recipes to extract ingredients, and deduplicates.
    @MainActor
    static func generateFromMealPlan(
        weekStart: Date,
        kidIds: [String],
        appState: AppState
    ) async throws -> [GroceryItem] {
        let calendar = Calendar.current
        let dates = (0..<7).map { offset in
            calendar.date(byAdding: .day, value: offset, to: weekStart)!
        }

        // Collect all food IDs from plan entries for the week
        var foodIdCounts: [String: Int] = [:]
        for date in dates {
            for kidId in kidIds {
                let entries = appState.planEntriesForDate(date, kidId: kidId)
                for entry in entries {
                    foodIdCounts[entry.foodId, default: 0] += 1
                }
            }
        }

        // Build grocery items from foods, deduplicating
        var groceryItems: [GroceryItem] = []
        let existingNames = Set(appState.groceryItems.map { $0.name.lowercased() })

        for (foodId, count) in foodIdCounts {
            guard let food = appState.foods.first(where: { $0.id == foodId }) else { continue }

            // Skip if already on grocery list
            if existingNames.contains(food.name.lowercased()) { continue }

            let item = GroceryItem(
                id: UUID().uuidString,
                userId: "",
                name: food.name,
                category: food.category,
                quantity: Double(count),
                unit: food.unit ?? "servings",
                checked: false,
                aisle: food.aisle,
                autoGenerated: true,
                // US-263: best-effort aisle assignment from the food's
                // FoodCategory. US-266 will refine with name-based lookup
                // for items where the category alone can't pinpoint the
                // store section (e.g. "snack" -> snacks vs candy vs crackers).
                aisleSection: aisleFromFoodCategory(food.category).rawValue
            )

            groceryItems.append(item)
        }

        // US-265: Pull ingredients from each planned recipe. Structured
        // rows from `recipe_ingredients` are preferred — they carry qty,
        // unit, and an optional foodId, so we can dedupe against pantry
        // and the existing grocery list cleanly. Fall back to the legacy
        // `additional_ingredients` comma-string for unmigrated recipes.
        let recipeIds = Set(appState.planEntries.compactMap(\.recipeId))
        for recipe in appState.recipes where recipeIds.contains(recipe.id) {
            if !recipe.ingredients.isEmpty {
                appendStructuredIngredients(
                    recipe.ingredients,
                    into: &groceryItems,
                    existingNames: existingNames,
                    pantry: appState.foods
                )
            } else if let ingredientsStr = recipe.additionalIngredients, !ingredientsStr.isEmpty {
                appendLegacyIngredients(
                    ingredientsStr,
                    into: &groceryItems,
                    existingNames: existingNames
                )
            }
        }

        return groceryItems.sorted { $0.category < $1.category }
    }

    /// US-265: Append structured RecipeIngredient rows to the build list.
    /// Skips ingredients already on the grocery list (by name) or already
    /// in the pantry (by `foodId`, when set). Carries qty + unit through
    /// so the budget view can compute weekly totals correctly.
    private static func appendStructuredIngredients(
        _ ingredients: [RecipeIngredient],
        into groceryItems: inout [GroceryItem],
        existingNames: Set<String>,
        pantry: [Food]
    ) {
        let pantryFoodIds = Set(pantry.map(\.id))
        for ing in ingredients {
            let nameLower = ing.name.lowercased()
            if existingNames.contains(nameLower) { continue }
            if groceryItems.contains(where: { $0.name.lowercased() == nameLower }) { continue }
            // If the ingredient is linked to a pantry food the user already
            // has on hand, skip it. US-262 will later add quantity-aware
            // skipping (only skip if pantry has enough for the planned servings).
            if let fid = ing.foodId, pantryFoodIds.contains(fid) { continue }

            // Pull a category hint from the linked Food when available;
            // otherwise the aisle classifier (US-266) will refine on save.
            let linkedFood = ing.foodId.flatMap { fid in
                pantry.first(where: { $0.id == fid })
            }
            let category = linkedFood?.category ?? "other"
            let aisle = GroceryAisle.fromLegacyCategory(category)

            groceryItems.append(GroceryItem(
                id: UUID().uuidString,
                userId: "",
                name: ing.name,
                category: category,
                quantity: ing.quantity ?? 1,
                unit: ing.unit ?? "",
                checked: false,
                autoGenerated: true,
                aisleSection: aisle.rawValue
            ))
        }
    }

    /// Legacy fallback: parse `recipes.additional_ingredients` comma
    /// string into grocery items. Used for recipes that haven't been
    /// edited since US-265 shipped, where structured rows don't exist.
    private static func appendLegacyIngredients(
        _ legacy: String,
        into groceryItems: inout [GroceryItem],
        existingNames: Set<String>
    ) {
        let names = legacy.split(separator: ",").map {
            $0.trimmingCharacters(in: .whitespaces)
        }
        for ingredient in names {
            let nameLower = ingredient.lowercased()
            if existingNames.contains(nameLower) { continue }
            if groceryItems.contains(where: { $0.name.lowercased() == nameLower }) { continue }
            groceryItems.append(GroceryItem(
                id: UUID().uuidString,
                userId: "",
                name: ingredient,
                category: "other",
                quantity: 1,
                unit: "",
                checked: false,
                autoGenerated: true,
                aisleSection: GroceryAisle.other.rawValue
            ))
        }
    }

    /// US-263: best-effort mapping from the legacy 6-bucket FoodCategory
    /// to the 32-aisle taxonomy. Used when generating from meal plan
    /// foods where we don't yet have item-level classification.
    private static func aisleFromFoodCategory(_ raw: String) -> GroceryAisle {
        switch FoodCategory(rawValue: raw) {
        case .protein:   return .meatDeli
        case .carb:      return .pasta
        case .dairy:     return .dairy
        case .fruit:     return .produce
        case .vegetable: return .produce
        case .snack:     return .snacks
        case .none:      return .other
        }
    }

    /// Adds all generated items to the grocery list via AppState.
    @MainActor
    static func addGeneratedItems(
        _ items: [GroceryItem],
        appState: AppState
    ) async throws {
        for item in items {
            try await appState.addGroceryItem(item)
        }

        let toast = ToastManager.shared
        toast.success("Grocery list updated", message: "Added \(items.count) items from meal plan.")
        HapticManager.success()
    }
}
