-- Agentic OS — US-481: knowledge base with pgvector for RAG
-- Additive only. Admin-only RLS. Embeddings are 1536-dim (OpenAI
-- text-embedding-3-small), generated by the agent-knowledge-ingest function.

-- Enable pgvector if not already enabled (Supabase ships it under `extensions`).
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.agent_knowledge (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  embedding vector(1536),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_source ON public.agent_knowledge(source);
-- Approximate-nearest-neighbour index for cosine distance searches.
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_embedding
  ON public.agent_knowledge USING hnsw (embedding vector_cosine_ops);

DROP TRIGGER IF EXISTS update_agent_knowledge_updated_at ON public.agent_knowledge;
CREATE TRIGGER update_agent_knowledge_updated_at
  BEFORE UPDATE ON public.agent_knowledge
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.agent_knowledge ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage agent knowledge"
  ON public.agent_knowledge FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role = 'admin'
    )
  );

-- Cosine-similarity retrieval. Called by the RAG answer agent via the service
-- role (which bypasses RLS); similarity = 1 - cosine_distance.
CREATE OR REPLACE FUNCTION public.match_agent_knowledge(
  query_embedding vector(1536),
  match_count INT DEFAULT 5,
  min_similarity FLOAT DEFAULT 0.5
)
RETURNS TABLE (id UUID, title TEXT, content TEXT, similarity FLOAT)
LANGUAGE sql
STABLE
AS $$
  SELECT
    ak.id,
    ak.title,
    ak.content,
    1 - (ak.embedding <=> query_embedding) AS similarity
  FROM public.agent_knowledge ak
  WHERE ak.embedding IS NOT NULL
    AND 1 - (ak.embedding <=> query_embedding) >= min_similarity
  ORDER BY ak.embedding <=> query_embedding
  LIMIT GREATEST(match_count, 1);
$$;

COMMENT ON TABLE public.agent_knowledge IS 'Agentic OS: RAG knowledge base (product docs/FAQ) with pgvector embeddings';
COMMENT ON FUNCTION public.match_agent_knowledge IS 'Agentic OS: cosine-similarity retrieval over agent_knowledge';
