package com.eatpal.app.domain

import com.eatpal.app.models.GroceryItem
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Kotlin port of iOS `GroceryGeneratorService`. Walks a week of plan entries,
 * tallies per-food counts, merges with `recipe.additional_ingredients`, and
 * deduplicates against the existing grocery list. Pure domain logic — reads
 * the current state snapshot from [AppStateStore], caller persists via
 * [AppStateStore.addGroceryItem].
 */
@Singleton
class GroceryGeneratorService @Inject constructor(
    private val appState: AppStateStore,
) {
    /**
     * Generates a deduped list of grocery items for [weekStart] (inclusive)
     * through the following 6 days, across the provided [kidIds]. Items are
     * sorted by category — same shape iOS returns.
     */
    fun generateFromMealPlan(weekStart: LocalDate, kidIds: List<String>): List<GroceryItem> {
        val plan = appState.planEntries.value
        val foods = appState.foods.value
        val recipes = appState.recipes.value
        val existing = appState.groceryItems.value

        val fmt = DateTimeFormatter.ISO_LOCAL_DATE
        val weekDates = (0..6).map { weekStart.plusDays(it.toLong()).format(fmt) }.toSet()

        // Tally food_id references within the week for the selected kids.
        val foodIdCounts = mutableMapOf<String, Int>()
        val relevantEntries = plan.filter { it.date in weekDates && it.kidId in kidIds }
        for (entry in relevantEntries) {
            foodIdCounts[entry.foodId] = (foodIdCounts[entry.foodId] ?: 0) + 1
        }

        val existingNames = existing.map { it.name.trim().lowercase() }.toMutableSet()
        val result = mutableListOf<GroceryItem>()

        for ((foodId, count) in foodIdCounts) {
            val food = foods.firstOrNull { it.id == foodId } ?: continue
            val lowered = food.name.trim().lowercase()
            if (lowered in existingNames) continue
            existingNames += lowered
            result += GroceryItem(
                id = UUID.randomUUID().toString(),
                userId = "",
                name = food.name,
                category = food.category,
                quantity = count.toDouble(),
                unit = food.unit ?: "servings",
                checked = false,
                aisle = food.aisle,
                autoGenerated = true,
                addedVia = "meal_plan",
            )
        }

        // Fold in recipe additional_ingredients, treating each comma-split
        // entry as an implicit "1 ea" item.
        val recipeIds = relevantEntries.mapNotNull { it.recipeId }.toSet()
        for (recipe in recipes.filter { it.id in recipeIds }) {
            val extras = recipe.additionalIngredients?.takeIf { it.isNotBlank() } ?: continue
            for (rawIngredient in extras.split(",")) {
                val ingredient = rawIngredient.trim()
                if (ingredient.isBlank()) continue
                val lowered = ingredient.lowercase()
                if (lowered in existingNames) continue
                existingNames += lowered
                result += GroceryItem(
                    id = UUID.randomUUID().toString(),
                    userId = "",
                    name = ingredient,
                    category = "other",
                    quantity = 1.0,
                    unit = "",
                    checked = false,
                    autoGenerated = true,
                    addedVia = "meal_plan",
                )
            }
        }

        return result.sortedBy { it.category }
    }

    /**
     * Convenience writer — iterates the generated list and routes each add
     * through AppStateStore so offline queuing + optimistic UI apply.
     */
    suspend fun addGenerated(items: List<GroceryItem>) {
        for (item in items) {
            appState.addGroceryItem(item)
        }
    }
}
